package edu.nps.deep.beArtifactGui.d3;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class _ForceDirectedPanel extends VerticalLayout
{
  protected Label filenameLab;
  protected Label emailLab;
  protected Label graphFileLab;
  protected VerticalLayout graphVL;

  public _ForceDirectedPanel()
  {
    Design.read(this);
  }
}
